# Generated by Django 5.1.6 on 2025-03-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('notice_period', models.IntegerField()),
                ('current_ctc', models.FloatField()),
                ('expected_ctc', models.FloatField()),
                ('experience', models.FloatField()),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
    ]
